// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project1.API.Data;

#nullable disable

namespace Project1.API.Migrations
{
    [DbContext(typeof(Project1Context))]
    [Migration("20241025032501_TestSingleton")]
    partial class TestSingleton
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project1.API.Model.Creature", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Blurb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Singleton")
                        .HasColumnType("bit");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Bestiary");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Blurb = "A giant arthopod covered in heavy scales and venomous barbs.",
                            Height = 3.0,
                            Name = "Giant Scorpion",
                            Singleton = false,
                            Weight = 70.0
                        },
                        new
                        {
                            ID = 2,
                            Blurb = "A carnivorous spherical cactus who catches small insects by rolling over them.",
                            Height = 1.0,
                            Name = "Cactorb",
                            Singleton = false,
                            Weight = 20.0
                        },
                        new
                        {
                            ID = 3,
                            Blurb = "This mummified priest commands swarms of locusts to gather food and treasure to his tomb.",
                            Height = 1.0,
                            Name = "Locustus",
                            Singleton = true,
                            Weight = 20.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
